package modelo.entidad;
// Generated 10-Dec-2016 08:34:20 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Pago generated by hbm2java
 */
public class Pago  implements java.io.Serializable {


     private Integer idpago;
     private Usuario usuario;
     private Viaje viaje;
     private String numeroComprobante;
     private Double monto;
     private Date fechaPago;

    public Pago() {
         viaje = new Viaje();
    }

    public Pago(Usuario usuario, Viaje viaje, String numeroComprobante, Double monto, Date fechaPago) {
       this.usuario = usuario;
       this.viaje = viaje;
       this.numeroComprobante = numeroComprobante;
       this.monto = monto;
       this.fechaPago = fechaPago;
    }
   
    public Integer getIdpago() {
        return this.idpago;
    }
    
    public void setIdpago(Integer idpago) {
        this.idpago = idpago;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Viaje getViaje() {
        return this.viaje;
    }
    
    public void setViaje(Viaje viaje) {
        this.viaje = viaje;
    }
    public String getNumeroComprobante() {
        return this.numeroComprobante;
    }
    
    public void setNumeroComprobante(String numeroComprobante) {
        this.numeroComprobante = numeroComprobante;
    }
    public Double getMonto() {
        return this.monto;
    }
    
    public void setMonto(Double monto) {
        this.monto = monto;
    }
    public Date getFechaPago() {
        return this.fechaPago;
    }
    
    public void setFechaPago(Date fechaPago) {
        this.fechaPago = fechaPago;
    }




}


