package modelo.entidad;
// Generated 10-Dec-2016 08:34:20 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sitios generated by hbm2java
 */
public class Sitios  implements java.io.Serializable {


     private Integer idsitios;
     private Usuario usuario;
     private String nombre;
     private String direccion;
     private String descripcion;
     private Set<Viaje> viajes = new HashSet<Viaje>(0);

    public Sitios() {
    }

    public Sitios(Usuario usuario,String nombre, String direccion, String descripcion, Set<Viaje> viajes) {
       this.usuario = usuario;
        this.nombre = nombre;
       this.direccion = direccion;
       this.descripcion = descripcion;
       this.viajes = viajes;
    }
   
    public Integer getIdsitios() {
        return this.idsitios;
    }
    
      public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    
    public void setIdsitios(Integer idsitios) {
        this.idsitios = idsitios;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set<Viaje> getViajes() {
        return this.viajes;
    }
    
    public void setViajes(Set<Viaje> viajes) {
        this.viajes = viajes;
    }




}


