package modelo.entidad;
// Generated 10-Dec-2016 08:34:20 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Viaje generated by hbm2java
 */
public class Viaje  implements java.io.Serializable {


     private Integer idviaje;
     private Sitios sitios;
     private Usuario usuario;
     private String nombreCliente;
     private String nombre;
     private Date fechaViaje;
     private Double costo;
     private Boolean activo;
     private Set<Pago> pagos = new HashSet<Pago>(0);

    public Viaje() {
        sitios = new Sitios();
    }

    public Viaje(Sitios sitios, Usuario usuario, String nombreCliente, String nombre, Date fechaViaje, Double costo, Boolean activo, Set<Pago> pagos) {
       this.sitios = sitios;
       this.usuario = usuario;
       this.nombreCliente = nombreCliente;
       this.nombre = nombre;
       this.fechaViaje = fechaViaje;
       this.costo = costo;
       this.activo = activo;
       this.pagos = pagos;
    }
   
    public Integer getIdviaje() {
        return this.idviaje;
    }
    
    public void setIdviaje(Integer idviaje) {
        this.idviaje = idviaje;
    }
    public Sitios getSitios() {
        return this.sitios;
    }
    
    public void setSitios(Sitios sitios) {
        this.sitios = sitios;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getNombreCliente() {
        return this.nombreCliente;
    }
    
    public void setNombreCliente(String nombreCliente) {
        this.nombreCliente = nombreCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaViaje() {
        return this.fechaViaje;
    }
    
    public void setFechaViaje(Date fechaViaje) {
        this.fechaViaje = fechaViaje;
    }
    public Double getCosto() {
        return this.costo;
    }
    
    public void setCosto(Double costo) {
        this.costo = costo;
    }
    public Boolean getActivo() {
        return this.activo;
    }
    
    public void setActivo(Boolean activo) {
        this.activo = activo;
    }
    public Set<Pago> getPagos() {
        return this.pagos;
    }
    
    public void setPagos(Set<Pago> pagos) {
        this.pagos = pagos;
    }




}


