-- MySQL Script generated by MySQL Workbench
-- 12/11/16 23:58:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bdtur
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdtur
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdtur` DEFAULT CHARACTER SET utf8 ;
USE `bdtur` ;

-- -----------------------------------------------------
-- Table `bdtur`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtur`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `clave` VARCHAR(45) NULL DEFAULT NULL,
  `nombreCompleto` VARCHAR(45) NULL DEFAULT NULL,
  `fechaCreacion` DATE NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtur`.`sitios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtur`.`sitios` (
  `idsitios` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `direccion` VARCHAR(45) NULL DEFAULT NULL,
  `Descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idsitios`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtur`.`viaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtur`.`viaje` (
  `idviaje` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_cliente` VARCHAR(45) NULL DEFAULT NULL,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `fechaViaje` DATE NULL DEFAULT NULL,
  `costo` DOUBLE(10,2) NULL DEFAULT NULL,
  `idusuario` INT(11) NULL DEFAULT NULL,
  `idsitio` INT(11) NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idviaje`),
  INDEX `fk_viaje_usuario_idx` (`idusuario` ASC),
  INDEX `fk_viaje_sitios1_idx` (`idsitio` ASC),
  CONSTRAINT `fk_viaje_sitios1`
    FOREIGN KEY (`idsitio`)
    REFERENCES `bdtur`.`sitios` (`idsitios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viaje_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bdtur`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bdtur`.`pago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdtur`.`pago` (
  `idpago` INT(11) NOT NULL AUTO_INCREMENT,
  `idviaje` INT(11) NULL DEFAULT NULL,
  `numeroComprobante` VARCHAR(45) NULL DEFAULT NULL,
  `monto` DOUBLE(10,2) NULL DEFAULT NULL,
  `fechaPago` DATE NULL DEFAULT NULL,
  `idusuario` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idpago`),
  INDEX `fk_pago_viaje1_idx` (`idviaje` ASC),
  INDEX `fk_pago_usuario1_idx` (`idusuario` ASC),
  CONSTRAINT `fk_pago_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `bdtur`.`usuario` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_viaje1`
    FOREIGN KEY (`idviaje`)
    REFERENCES `bdtur`.`viaje` (`idviaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
